version: '4.0'
services:
  java_app:
    container_name: java_app
    image: java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres  # Update hostname to service name
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - KAFKA_URL=kafka:9092  # Kafka broker address
    depends_on:
      - java_db
      - kafka
      - zookeeper
    networks:
      - kafka-network

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kafka-network
  zookeeper:
    container_name: zookeeper
    image: ubuntu/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - kafka-network

  kafka:
    container_name: kafka
    image: ubuntu/kafka:latest
    ports:
      - 9092:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true  # Use existing external network

volumes:
  pgdata: {}